//! Request retries configurations
//!
//! To decide when to retry a request the `Session` can use any object which implements
//! the `RetryPolicy` trait.

use crate::errors::RequestAttemptError;
use crate::frame::types::Consistency;

/// Information about a failed request
#[non_exhaustive]
pub struct RequestInfo<'a> {
    /// The error with which the request failed.
    pub error: &'a RequestAttemptError,
    /// A request is idempotent if it can be applied multiple times without changing the result of the initial application.
    ///
    /// If set to `true` we can be sure that it is idempotent.
    ///
    /// If set to `false` it is unknown whether it is idempotent.
    pub is_idempotent: bool,
    /// Consistency with which the request failed.
    ///
    /// This is the consistency level of the attempt that just failed, which is not necessarily
    /// the one the statement was configured with: a previous [`RetryDecision`] may have already
    /// changed it.
    pub consistency: Consistency,
}

impl<'a> RequestInfo<'a> {
    /// Creates a new `RequestInfo` instance.
    #[cfg(all(scylla_unstable, feature = "unstable-python-rs"))]
    pub fn new(
        error: &'a RequestAttemptError,
        is_idempotent: bool,
        consistency: Consistency,
    ) -> Self {
        Self {
            error,
            is_idempotent,
            consistency,
        }
    }
}

/// Returned by implementations of RetryPolicy. Instructs the driver on what
/// to do about the request after it failed.
///
/// <div class="warning">
///
/// The retrying variants can change the consistency level used for the retry. The load balancing
/// plan, however, is computed once per request - from a
/// [`RoutingInfo`](crate::policies::load_balancing::RoutingInfo) holding the consistency level of
/// the *first* attempt - and is **not** recomputed when the level changes. A load balancing policy
/// that routes based on the consistency level (e.g. keeps the plan within the local datacenter for
/// `LOCAL_QUORUM`) will therefore hand out targets chosen for the original level, and the retry may
/// be sent to a target that does not satisfy the new one.
///
/// </div>
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum RetryDecision {
    /// Request will be sent to the same shard on the same host.
    RetrySameTarget(Option<Consistency>), // None means that the same consistency should be used as before
    /// Request will be sent to the next target generated by load balancing policy.
    RetryNextTarget(Option<Consistency>), // ditto
    /// Fails the whole request.
    DontRetry,
    /// Will cause the driver to return an empty successful response.
    IgnoreWriteError,
}

/// Specifies a policy used to decide when to retry a request
pub trait RetryPolicy: std::fmt::Debug + Send + Sync {
    /// Called for each new request, starts a session of deciding about retries
    fn new_session(&self) -> Box<dyn RetrySession>;

    /// Lets the driver recognise its own built-in policies by downcasting, so that
    /// the driver configuration report can describe them precisely. Implementations
    /// outside this crate keep the `None` default and are reported generically.
    ///
    /// Not part of the stable API; may change at any time.
    #[doc(hidden)]
    fn as_any(&self) -> Option<&dyn std::any::Any> {
        None
    }

    /// Name used to describe this policy generically in the driver configuration
    /// report. The default is the implementor's own type name, so no implementation
    /// is required.
    ///
    /// Not part of the stable API; may change at any time.
    #[doc(hidden)]
    fn reported_name(&self) -> &'static str {
        crate::policies::simple_type_name::<Self>()
    }
}

/// Used throughout a single request to decide when to retry it
/// After this request is finished it is destroyed or reset
pub trait RetrySession: Send + Sync {
    /// Called after the request failed - decide what to do next
    fn decide_should_retry(&mut self, request_info: RequestInfo) -> RetryDecision;

    /// Reset before using for a new request
    fn reset(&mut self);
}
