#![cfg_attr(
    not(all(scylla_unstable, feature = "unstable-reconnect-policy")),
    expect(unreachable_pub)
)]

//! Policy that controls delays between connection pool fill attempts.
//!
//! UNSTABLE API, guarded by `scylla_unstable` cfg and `unstable-reconnect-policy` feature.

use std::time::Duration;

/// Generated by [ReconnectPolicy] to control the delay between connection
/// attempts in a single connection pool.
///
/// In the current implementation, pool performs fills in batches.
/// [on_fill_error] is called if any connection attempt in the batch failed.
/// [on_successful_fill] is called if all connection attempts in the batch succeeded.
pub trait ReconnectPolicySession: Send + std::fmt::Debug {
    /// Tells the pool how long to wait before attempting to fill connections to the host.
    fn get_delay(&self) -> Duration;
    /// Called when all connection attempts in the batch succeeded.
    fn on_successful_fill(&mut self);
    /// Called when any connection attempt in the batch failed.
    fn on_fill_error(&mut self);
}

/// Policy for controlling delays between connection pool fill attempts.
///
/// Because such policy may require mutable state (to handle fill failures),
/// this trait is not used directly by connection pools. Instead, the only
/// purpose of this trait is to generate boxed instances of per-host policy objects.
/// The generated objects are used by a single pool, and so can have methods with `&mut self`.
pub trait ReconnectPolicy: Send + Sync + std::fmt::Debug {
    /// Returns a new instance of the policy for the single host.
    fn new_session(&self) -> Box<dyn ReconnectPolicySession>;
}

#[derive(Debug)]
struct HostExponentialReconnectPolicy {
    min_fill_backoff: Duration,
    max_fill_backoff: Duration,
    fill_backoff_multiplier: u32,
    current_delay: Duration,
}

impl ReconnectPolicySession for HostExponentialReconnectPolicy {
    fn get_delay(&self) -> Duration {
        self.current_delay
    }

    fn on_successful_fill(&mut self) {
        self.current_delay = self.min_fill_backoff;
    }

    fn on_fill_error(&mut self) {
        self.current_delay = std::cmp::min(
            self.max_fill_backoff,
            self.current_delay
                .saturating_mul(self.fill_backoff_multiplier),
        );
    }
}

/// Reconnect policy that exponentially increases the delay between connection pool fill attempts.
///
/// It has 3 parameters, that can all be configured:
/// - `min_fill_backoff`: minimum delay between fill attempts
/// - `max_fill_backoff`: maximum delay between fill attempts
/// - `fill_backoff_multiplier`: multiplier for increasing the delay between fill attempts
#[derive(Debug)]
pub struct ExponentialReconnectPolicy {
    min_fill_backoff: Duration,
    max_fill_backoff: Duration,
    fill_backoff_multiplier: u32,
}

#[cfg_attr(
    not(all(scylla_unstable, feature = "unstable-reconnect-policy")),
    expect(dead_code)
)]
impl ExponentialReconnectPolicy {
    /// Creates a new exponential reconnect policy with default values.
    pub fn new() -> Self {
        let min_fill_backoff = Duration::from_millis(50);
        Self {
            min_fill_backoff,
            max_fill_backoff: Duration::from_secs(10),
            fill_backoff_multiplier: 2,
        }
    }

    /// Changes `min_fill_backoff` to the given value.
    /// `min_fill_backoff` is the minimum delay between fill attempts.
    pub fn with_min_fill_backoff(mut self, value: Duration) -> Self {
        self.min_fill_backoff = value;
        self
    }

    /// Changes `max_fill_backoff` to the given value.
    /// `max_fill_backoff` is the maximum delay between fill attempts.
    pub fn with_max_fill_backoff(mut self, value: Duration) -> Self {
        self.max_fill_backoff = value;
        self
    }

    /// Changes `fill_backoff_multiplier` to the given value.
    /// `fill_backoff_multiplier` is the multiplier for increasing the delay between fill attempts.
    pub fn with_fill_backoff_multiplier(mut self, value: u32) -> Self {
        self.fill_backoff_multiplier = value;
        self
    }
}

impl Default for ExponentialReconnectPolicy {
    fn default() -> Self {
        Self::new()
    }
}

impl ReconnectPolicy for ExponentialReconnectPolicy {
    fn new_session(&self) -> Box<dyn ReconnectPolicySession> {
        Box::new(HostExponentialReconnectPolicy {
            min_fill_backoff: self.min_fill_backoff,
            max_fill_backoff: self.max_fill_backoff,
            fill_backoff_multiplier: self.fill_backoff_multiplier,
            current_delay: self.min_fill_backoff,
        })
    }
}
