/// Generates `scylla/src/book_tests.rs` from `docs/source/SUMMARY.md`.
///
/// For each book chapter that contains ```rust code blocks, a module with
/// `#![doc = include_str!("...")]` is emitted so that rustdoc compiles and
/// tests those code blocks alongside normal doctests.
///
/// Usage:
///     cargo run -p utils --bin generate_book_tests           # (re)generate the file
///     cargo run -p utils --bin generate_book_tests -- --check # exit 1 if file is stale
use std::fs;
use std::path::{Path, PathBuf};
use std::process;

// Relative path prefix from scylla/src/book_tests.rs to docs/source/
const INCLUDE_PREFIX: &str = "../../docs/source/";

const HEADER: &str = "\
// This file is autogenerated by utils/src/bin/generate_book_tests.rs
// Do not edit manually. Regenerate with:
//   cargo run -p utils --bin generate_book_tests

// Some book chapters contain Sphinx-specific ```{eval-rst} blocks that
// rustdoc interprets as invalid code block attributes.
#![allow(rustdoc::invalid_codeblock_attributes)]
";

// ---------------------------------------------------------------------------
// Repo root discovery
// ---------------------------------------------------------------------------

fn find_repo_root() -> PathBuf {
    let mut dir = std::env::current_dir().expect("Failed to get current directory");
    loop {
        if dir.join("docs/source/SUMMARY.md").is_file() {
            return dir;
        }
        if !dir.pop() {
            eprintln!(
                "ERROR: Could not find repository root \
                 (looking for docs/source/SUMMARY.md)"
            );
            process::exit(1);
        }
    }
}

// ---------------------------------------------------------------------------
// SUMMARY.md parser
// ---------------------------------------------------------------------------

/// Extract the `.md` path from a SUMMARY.md line, if present.
///
/// Matches two patterns:
///   - `  - [Title](path/to/file.md)`   (list entry, any indentation)
///   - `[Title](path/to/file.md)`        (top-level page, no indentation)
fn extract_md_path(line: &str) -> Option<&str> {
    let trimmed = line.trim_end();
    let stripped = trimmed.trim_start();

    // Determine if this is a list entry ("- [...]") or a top-level link ("[...]").
    let rest = if let Some(after_dash) = stripped.strip_prefix("- ") {
        after_dash
    } else if trimmed.starts_with('[') {
        // Top-level: only match when there is no leading whitespace.
        trimmed
    } else {
        return None;
    };

    if !rest.starts_with('[') {
        return None;
    }

    let link_start = rest.find("](")?;
    let path_start = link_start + 2;
    let path_end = path_start + rest[path_start..].find(')')?;
    let path = &rest[path_start..path_end];

    if path.ends_with(".md") {
        Some(path)
    } else {
        None
    }
}

/// Return a flat list of `.md` paths referenced in SUMMARY.md, in order.
fn parse_summary(summary_path: &Path) -> Vec<String> {
    let content = fs::read_to_string(summary_path).expect("Failed to read SUMMARY.md");
    content
        .lines()
        .filter_map(|line| extract_md_path(line).map(String::from))
        .collect()
}

// ---------------------------------------------------------------------------
// Rust code block detection
// ---------------------------------------------------------------------------

fn has_rust_code_blocks(path: &Path) -> bool {
    let content = fs::read_to_string(path).expect("Failed to read markdown file");
    content.lines().any(|line| line.starts_with("```rust"))
}

// ---------------------------------------------------------------------------
// Module name derivation
// ---------------------------------------------------------------------------

/// Convert a file stem (e.g. `0.11-serialization`) to a valid Rust identifier.
fn path_to_module_name(stem: &str) -> String {
    let name: String = stem
        .chars()
        .map(|c| if c == '-' || c == '.' { '_' } else { c })
        .collect();
    // Rust identifiers cannot start with a digit.
    if name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("_{name}")
    } else {
        name
    }
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

fn generate(summary_paths: &[String], source_dir: &Path) -> String {
    let mut lines: Vec<String> = vec![HEADER.to_string()];

    // Group paths by directory (first path component).
    // Paths without a directory (e.g. "index.md") go under a virtual
    // top-level group (empty string key).
    let mut groups: Vec<(String, Vec<String>)> = Vec::new();

    for rel_path in summary_paths {
        let md_abs = source_dir.join(rel_path);
        if !md_abs.is_file() {
            eprintln!("WARNING: {rel_path} referenced in SUMMARY.md does not exist");
            continue;
        }
        if !has_rust_code_blocks(&md_abs) {
            continue;
        }

        let group = match rel_path.find('/') {
            Some(pos) => rel_path[..pos].to_string(),
            None => String::new(),
        };

        if let Some(entry) = groups.iter_mut().find(|(g, _)| *g == group) {
            entry.1.push(rel_path.clone());
        } else {
            groups.push((group, vec![rel_path.clone()]));
        }
    }

    for (group, paths) in &groups {
        let has_group = !group.is_empty();

        if has_group {
            let group_mod = path_to_module_name(group);
            lines.push(format!("mod {group_mod} {{"));
        }

        for rel_path in paths {
            let file_name = rel_path.rsplit('/').next().unwrap();
            let stem = file_name.strip_suffix(".md").unwrap();
            let mod_name = path_to_module_name(stem);
            let include = format!("{INCLUDE_PREFIX}{rel_path}");

            if has_group {
                lines.push(format!("    mod {mod_name} {{"));
                lines.push(format!("        #![doc = include_str!(\"{include}\")]"));
                lines.push("    }".to_string());
            } else {
                lines.push(format!("mod {mod_name} {{"));
                lines.push(format!("    #![doc = include_str!(\"{include}\")]"));
                lines.push("}".to_string());
            }
        }

        if has_group {
            lines.push("}".to_string());
        }

        lines.push(String::new());
    }

    lines.join("\n")
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fn main() {
    let check_mode = std::env::args().any(|a| a == "--check");

    let repo_root = find_repo_root();
    let summary_path = repo_root.join("docs/source/SUMMARY.md");
    let source_dir = repo_root.join("docs/source");
    let output_path = repo_root.join("scylla/src/book_tests.rs");

    if !summary_path.is_file() {
        eprintln!("ERROR: SUMMARY.md not found at {}", summary_path.display());
        process::exit(1);
    }

    let summary_paths = parse_summary(&summary_path);
    let content = generate(&summary_paths, &source_dir);

    if check_mode {
        if !output_path.is_file() {
            eprintln!(
                "ERROR: {} does not exist. Run without --check to generate it.",
                output_path.display()
            );
            process::exit(1);
        }
        let existing =
            fs::read_to_string(&output_path).expect("Failed to read existing output file");
        if existing == content {
            println!("book_tests.rs is up to date.");
        } else {
            eprintln!("ERROR: {} is out of date.", output_path.display());
            eprintln!("Regenerate it with:  cargo run -p utils --bin generate_book_tests");
            process::exit(1);
        }
    } else {
        fs::write(&output_path, &content).expect("Failed to write output file");
        println!("Generated {}", output_path.display());
    }
}
