[package]
edition = "2024"
name = "examples"
publish = false
version = "0.0.0"
rust-version = "1.88"

[dev-dependencies]
anyhow = "1.0.33"
futures = "0.3.6"
openssl = "0.10.70"
rustyline = "16"
rustyline-derive = "0.11"
scylla = { path = "../scylla", features = [
    "openssl-010",
    "rustls-023",
    "chrono-04",
    "time-03",
    "metrics",
    "unstable-client-routes",
] }
tokio = { version = "1.34", features = ["full"] }
tracing = { version = "0.1.25", features = ["log"] }
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
time = { version = "0.3.22" }
uuid = "1.0"
tower = "0.5"
rand = "0.9.0"
env_logger = "0.11"
rustls = "0.23"

[[example]]
name = "auth"
path = "auth.rs"

[[example]]
name = "basic"
path = "basic.rs"

[[example]]
name = "client_routes"
path = "client_routes.rs"

[[example]]
name = "compare_tokens"
path = "compare_tokens.rs"

[[example]]
name = "cql_time_types"
path = "cql_time_types.rs"

[[example]]
name = "cqlsh_rs"
path = "cqlsh_rs.rs"

[[example]]
name = "custom_deserialization"
path = "custom_deserialization.rs"

[[example]]
name = "custom_load_balancing_policy"
path = "custom_load_balancing_policy.rs"

[[example]]
name = "custom_serialization"
path = "custom_serialization.rs"

[[example]]
name = "enforce_coordinator"
path = "enforce_coordinator.rs"

[[example]]
name = "execution_profile"
path = "execution_profile.rs"

[[example]]
name = "get_by_name"
path = "get_by_name.rs"

[[example]]
name = "logging_via_log"
path = "logging_via_log.rs"

[[example]]
name = "logging_via_tracing"
path = "logging_via_tracing.rs"

[[example]]
name = "metrics"
path = "metrics.rs"

[[example]]
name = "parallel"
path = "parallel.rs"

[[example]]
name = "query_history"
path = "query_history.rs"

[[example]]
name = "schema_agreement"
path = "schema_agreement.rs"

[[example]]
name = "select_paging"
path = "select_paging.rs"

[[example]]
name = "speculative_execution"
path = "speculative_execution.rs"

[[example]]
name = "tls_openssl"
path = "tls_openssl.rs"

[[example]]
name = "tls_rustls"
path = "tls_rustls.rs"

[[example]]
name = "tower"
path = "tower.rs"

[[example]]
name = "tracing"
path = "tracing.rs"

[[example]]
name = "user_defined_type"
path = "user_defined_type.rs"

[package.metadata.cargo-semver-checks.lints]
workspace = true
