[package]
name = "scylla-ccm-bridge"
version = "0.0.1"
edition = "2024"
rust-version = "1.88"
description = "CCM (Cassandra Cluster Manager) bridge for testing ScyllaDB Drivers"
repository = "https://github.com/scylladb/scylla-rust-driver"
readme = "../README.md"
license = "MIT OR Apache-2.0"

[lints.rust]
unreachable_pub = "warn"
missing-docs = "warn"

[features]
default = []
# Enables facilities that require ScyllaDB Rust Driver as a dependency.
driver = ["dep:scylla"]
# Enables testing facilities for client routes.
unstable-client-routes = [
    "driver",
    "scylla/unstable-client-routes",
    "dep:scylla-cql",
    "dep:scylla-proxy",
]

[dependencies]
tokio = { version = "1.40", features = [
    "process",
    "fs",
    "io-util",
    "rt",
    "sync",
    "macros",
] }
anyhow = "1.0.98"
futures = "0.3.6"
bytes = "1.10"
rand = "0.9.0"
tempfile = "3.19"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }
uuid = { version = "1.0", features = ["v4"] }
itertools = "0.15.0"

# Needed for client routes feature only
scylla = { version = "1.8.0", path = "../scylla", optional = true }
scylla-cql = { version = "1.8.0", path = "../scylla-cql", optional = true }
scylla-proxy = { version = "0.0.7", path = "../scylla-proxy", optional = true }

[package.metadata.cargo-semver-checks.lints]
workspace = true

[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
