//! Prints a table of `size_of` for every public error type defined in
//! `scylla::errors`, discovered automatically at build time by parsing
//! `scylla/src/errors.rs` with `syn`.
//!
//! The list of types is generated by `build.rs` into `$OUT_DIR/error_types.rs`
//! and `include!`-ed below — no manual maintenance required.
//!
//! Run with:
//!   cargo run -p analyze_errors_size

fn main() {
    // `include!` splices in a `&[(&str, usize)]` literal generated by build.rs.
    let rows: &[(&str, usize)] = include!(concat!(env!("OUT_DIR"), "/error_types.rs"));

    let mut rows: Vec<(&str, usize)> = rows.to_vec();
    // Sort largest first so the heaviest types stand out.
    rows.sort_by_key(|&(_, size)| std::cmp::Reverse(size));

    let name_col = rows
        .iter()
        .map(|(name, _)| name.len())
        .max()
        .unwrap_or(4)
        .max("type".len());
    let size_col = "size (bytes)".len();

    let separator = format!("+-{}-+-{}-+", "-".repeat(name_col), "-".repeat(size_col));

    println!("{separator}");
    println!("| {:<name_col$} | {:>size_col$} |", "type", "size (bytes)");
    println!("{separator}");
    for (name, size) in &rows {
        println!("| {:<name_col$} | {:>size_col$} |", name, size);
    }
    println!("{separator}");
}
