// This file is autogenerated by utils/src/bin/generate_book_tests.rs
// Do not edit manually. Regenerate with:
//   cargo run -p utils --bin generate_book_tests

// Some book chapters contain Sphinx-specific ```{eval-rst} blocks that
// rustdoc interprets as invalid code block attributes.
#![allow(rustdoc::invalid_codeblock_attributes)]

mod quickstart {
    mod create_project {
        #![doc = include_str!("../../docs/source/quickstart/create-project.md")]
    }
    mod example {
        #![doc = include_str!("../../docs/source/quickstart/example.md")]
    }
}

mod migration_guides {
    mod _0_11_serialization {
        #![doc = include_str!("../../docs/source/migration-guides/0.11-serialization.md")]
    }
    mod _0_15_deserialization {
        #![doc = include_str!("../../docs/source/migration-guides/0.15-deserialization.md")]
    }
}

mod connecting {
    mod connecting {
        #![doc = include_str!("../../docs/source/connecting/connecting.md")]
    }
    mod compression {
        #![doc = include_str!("../../docs/source/connecting/compression.md")]
    }
    mod authentication {
        #![doc = include_str!("../../docs/source/connecting/authentication.md")]
    }
    mod tls {
        #![doc = include_str!("../../docs/source/connecting/tls.md")]
    }
}

mod statements {
    mod unprepared {
        #![doc = include_str!("../../docs/source/statements/unprepared.md")]
    }
    mod values {
        #![doc = include_str!("../../docs/source/statements/values.md")]
    }
    mod result {
        #![doc = include_str!("../../docs/source/statements/result.md")]
    }
    mod prepared {
        #![doc = include_str!("../../docs/source/statements/prepared.md")]
    }
    mod batch {
        #![doc = include_str!("../../docs/source/statements/batch.md")]
    }
    mod paged {
        #![doc = include_str!("../../docs/source/statements/paged.md")]
    }
    mod lwt {
        #![doc = include_str!("../../docs/source/statements/lwt.md")]
    }
    mod usekeyspace {
        #![doc = include_str!("../../docs/source/statements/usekeyspace.md")]
    }
    mod schema_agreement {
        #![doc = include_str!("../../docs/source/statements/schema-agreement.md")]
    }
    mod timeouts {
        #![doc = include_str!("../../docs/source/statements/timeouts.md")]
    }
}

mod execution_profiles {
    mod create_and_use {
        #![doc = include_str!("../../docs/source/execution-profiles/create-and-use.md")]
    }
    mod maximal_example {
        #![doc = include_str!("../../docs/source/execution-profiles/maximal-example.md")]
    }
    mod priority {
        #![doc = include_str!("../../docs/source/execution-profiles/priority.md")]
    }
    mod remap {
        #![doc = include_str!("../../docs/source/execution-profiles/remap.md")]
    }
}

mod data_types {
    mod primitive {
        #![doc = include_str!("../../docs/source/data-types/primitive.md")]
    }
    mod text {
        #![doc = include_str!("../../docs/source/data-types/text.md")]
    }
    mod counter {
        #![doc = include_str!("../../docs/source/data-types/counter.md")]
    }
    mod blob {
        #![doc = include_str!("../../docs/source/data-types/blob.md")]
    }
    mod inet {
        #![doc = include_str!("../../docs/source/data-types/inet.md")]
    }
    mod uuid {
        #![doc = include_str!("../../docs/source/data-types/uuid.md")]
    }
    mod timeuuid {
        #![doc = include_str!("../../docs/source/data-types/timeuuid.md")]
    }
    mod date {
        #![doc = include_str!("../../docs/source/data-types/date.md")]
    }
    mod time {
        #![doc = include_str!("../../docs/source/data-types/time.md")]
    }
    mod timestamp {
        #![doc = include_str!("../../docs/source/data-types/timestamp.md")]
    }
    mod duration {
        #![doc = include_str!("../../docs/source/data-types/duration.md")]
    }
    mod decimal {
        #![doc = include_str!("../../docs/source/data-types/decimal.md")]
    }
    mod varint {
        #![doc = include_str!("../../docs/source/data-types/varint.md")]
    }
    mod collections {
        #![doc = include_str!("../../docs/source/data-types/collections.md")]
    }
    mod tuple {
        #![doc = include_str!("../../docs/source/data-types/tuple.md")]
    }
    mod udt {
        #![doc = include_str!("../../docs/source/data-types/udt.md")]
    }
}

mod load_balancing {
    mod load_balancing {
        #![doc = include_str!("../../docs/source/load-balancing/load-balancing.md")]
    }
    mod default_policy {
        #![doc = include_str!("../../docs/source/load-balancing/default-policy.md")]
    }
}

mod retry_policy {
    mod retry_policy {
        #![doc = include_str!("../../docs/source/retry-policy/retry-policy.md")]
    }
    mod fallthrough {
        #![doc = include_str!("../../docs/source/retry-policy/fallthrough.md")]
    }
    mod default {
        #![doc = include_str!("../../docs/source/retry-policy/default.md")]
    }
    mod downgrading_consistency {
        #![doc = include_str!("../../docs/source/retry-policy/downgrading-consistency.md")]
    }
}

mod speculative_execution {
    mod simple {
        #![doc = include_str!("../../docs/source/speculative-execution/simple.md")]
    }
    mod percentile {
        #![doc = include_str!("../../docs/source/speculative-execution/percentile.md")]
    }
}

mod metrics {
    mod metrics {
        #![doc = include_str!("../../docs/source/metrics/metrics.md")]
    }
}

mod logging {
    mod logging {
        #![doc = include_str!("../../docs/source/logging/logging.md")]
    }
}

mod tracing {
    mod basic {
        #![doc = include_str!("../../docs/source/tracing/basic.md")]
    }
    mod paged {
        #![doc = include_str!("../../docs/source/tracing/paged.md")]
    }
    mod prepare {
        #![doc = include_str!("../../docs/source/tracing/prepare.md")]
    }
    mod query_history {
        #![doc = include_str!("../../docs/source/tracing/query-history.md")]
    }
}

mod schema {
    mod schema {
        #![doc = include_str!("../../docs/source/schema/schema.md")]
    }
}
