name: "Docs / Build PR"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  pull_request:
    branches:
      - main
      - 'branch-*'
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'
      - name: Set up env
        run: make -C docs setupenv
      - name: Build docs
        run: make -C docs test
      - name: Show preprocessing changes
        run: diff -r docs/source docs/_source || true
